{
 "title": "btcnode-metrics",
 "description": "Grafana dashboard companion for [btcnode-prom-metrics](https://crates.io/crates/btcnode-prom-metrics)",
 "tags": [
  "bitcoin",
  "prometheus",
  "btcnode-metrics",
  "bitcoin-metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "btcnode_metrics_version_version",
    "label": "btcnode-metrics",
    "query": {
     "query": "label_values(btcnode_metrics_version,version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_blocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_mempool_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bitcoin node version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "bitcoin_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blockchain Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_size_on_disk_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bitcoin_mempool_usage_bytes / bitcoin_mempool_max_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics gatherer uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_node_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Blocks",
   "type": "timeseries",
   "description": "Total number of Blocks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "bitcoin_blocks", "legendFormat": "Blocks" },
    { "expr": "bitcoin_headers", "legendFormat": "Headers" }
   ]
  },
  {
   "title": "Block Creation Rate",
   "type": "gauge",
   "description": "Number of blocks created",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "blocks/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bitcoin_blocks[3h]) * 3600",
     "legendFormat": "3h"
    },
    {
     "expr": "rate(bitcoin_blocks[6h]) * 3600",
     "legendFormat": "6h"
    },
    {
     "expr": "rate(bitcoin_blocks[12h]) * 3600",
     "legendFormat": "12h"
    },
    {
     "expr": "rate(bitcoin_blocks[7d]) * 3600 * 24",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Transaction Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "transac/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bitcoin_chain_tx_rate_per_second[30m])",
     "legendFormat": "30m"
    },
    {
     "expr": "rate(bitcoin_chain_tx_rate_per_second[1h])",
     "legendFormat": "1h"
    },
    {
     "expr": "rate(bitcoin_chain_tx_rate_per_second[3h])",
     "legendFormat": "3h"
    },
    {
     "expr": "{\"rate(bitcoin_chain_tx_rate_per_second[3h])\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fee Rate",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sat/byte" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bitcoin_fee_estimate_2_blocks_btc_per_kvb",
     "legendFormat": "2 blocks"
    },
    {
     "expr": "bitcoin_fee_estimate_6_blocks_btc_per_kvb",
     "legendFormat": "5 blocks"
    },
    {
     "expr": "bitcoin_fee_estimate_12_blocks_btc_per_kvb",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_fee_estimate_144_blocks_btc_per_kvb",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Mempool Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "bitcoin_mempool_max_bytes", "legendFormat": "Mempool Max" },
    { "expr": "bitcoin_mempool_usage_bytes", "legendFormat": "Mempool Usage" }
   ]
  },
  {
   "title": "Transactions in Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "bitcoin_mempool_transactions", "legendFormat": "Transactions" }
   ]
  },
  { "title": "P2P Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "bitcoin_connections_in", "legendFormat": "Connections In" },
    { "expr": "bitcoin_connections_out", "legendFormat": "Connections Out" }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "bitcoin_connections", "legendFormat": "Connections" }
   ]
  },
  { "title": "Bitcoind Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bitcoin_collector_last_scrape_duration_seconds",
     "legendFormat": "Scrape Time"
    }
   ]
  }
 ]
}